---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      tags: ['dock']

  tasks:

    - name: Clone dotfiles repository
      tags: ['dotfiles']
      git:
        repo: git@github.com:michaelbarton/dotfiles.git
        dest: ~/.dotfiles
        clone: yes
        update: yes

    - name: Update OSX defaults
      tags: ['osx']
      ansible.builtin.include_tasks: tasks/osx_defaults.yml

