---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - asdf
  - aspell
  - basictex
  - bat
  - cmake
  - coreutils
  - docker
  - docker-compose
  - dockutil
  - exa
  - fd
  - ffmpeg
  - fish
  - fzf
  - gh
  - htop
  - java
  - jq
  - just
  - mutt
  - neovim
  - offlineimap
  - openssl@3
  - parallel
  - pngcrush
  - psgrep
  - r
  - ripgrep
  - sqlite
  - starship
  - stow
  - svn
  - tmux
  - trash
  - tree
  - urlview
  - w3m
  - wget
  - zopfli
homebrew_cask_apps:
  - cleanmymac
  - dropbox
  - evernote
  - font-fira-code
  - font-fira-code-nerd-font
  - font-fira-mono
  - font-fira-mono-for-powerline
  - font-fira-mono-nerd-font
  - font-fira-sans
  - font-fira-sans-condensed
  - font-fira-sans-extra-condensed
  - font-inconsolata-dz-for-powerline
  - font-raleway
  - iterm2
  - pycharm-ce
  - rectangle
  - signal
  - spotify
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
homebrew_cask_appdir: /Applications
homebrew_upgrade_all_packages: true

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Safari
  - Maps
  - Mail
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Spotify
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages
  - App Store
  - Music
dockitems_persist:
  - name: Spotify
    path: "/Applications/Spotify.app/"
  - name: iTerm2
    path: "/Applications/iTerm.app/"

