---
- name: Provision macOS development environment
  hosts: localhost
  connection: local
  vars_files:
    - default.config.yml
  vars:
    homebrew_install_if_missing: false
    homebrew_check_for_updates: true
  tasks:
    - name: Check for local modifications in dotfiles repository
      tags: ["dotfiles"]
      ansible.builtin.command:
        cmd: git -C {{ ansible_env.HOME }}/.dotfiles diff --quiet
      register: dotfiles_status
      changed_when: false
      failed_when: false

    - name: Clone dotfiles repository
      tags: ["dotfiles"]
      ansible.builtin.git:
        repo: git@github.com:michaelbarton/dotfiles.git
        dest: "{{ ansible_env.HOME }}/.dotfiles"
        update: true
      when: dotfiles_status.rc is not defined or dotfiles_status.rc == 0

    - name: Ensure configured Homebrew taps are tapped
      tags: ["homebrew"]
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_taps }}"
      when: homebrew_taps | length > 0

    - name: Install Homebrew packages
      tags: ["homebrew"]
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_installed_packages }}"
      when: homebrew_installed_packages | length > 0

    - name: Install Homebrew cask applications
      tags: ["homebrew"]
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_cask_apps }}"
      when: homebrew_cask_apps | length > 0

    - name: Link homebrew dependencies
      tags: ["homebrew"]
      become: true
      ansible.builtin.file:
        src: "{{ homebrew_prefix }}/opt/openjdk/libexec/openjdk.jdk"
        dest: "/Library/Java/JavaVirtualMachines/openjdk.jdk"
        state: link
      vars:
        homebrew_prefix: "{{ '/opt/homebrew' if ansible_machine == 'arm64' else '/usr/local' }}"

    - name: Update macOS defaults
      tags: ["osx"]
      ansible.builtin.include_tasks: tasks/osx_defaults.yml

    - name: Configure Dock
      tags: ["dock"]
      ansible.builtin.include_role:
        name: geerlingguy.mac.dock

    - name: Upgrade all Homebrew packages
      tags: ["homebrew", "cleanup"]
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Remove outdated Homebrew package versions
      tags: ["homebrew", "cleanup"]
      ansible.builtin.command: brew cleanup
      register: brew_cleanup
      changed_when: brew_cleanup.stdout != ""
