---
- hosts: localhost
  connection: local
  vars_files:
    - default.config.yml
  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.dock
  tasks:
    - name: Clone dotfiles repository
      tags: ['dotfiles']
      git:
        repo: git@github.com:michaelbarton/dotfiles.git
        dest: "{{ ansible_env.HOME }}/.dotfiles"
        update: yes

    - name: Update OSX defaults
      tags: ['osx']
      include_tasks: tasks/osx_defaults.yml

    - name: Link homebrew dependencies
      tags: ['homebrew']
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { src: "/opt/homebrew/opt/openjdk/libexec/openjdk.jdk", dest: "/Library/Java/JavaVirtualMachines/openjdk.jdk" }

