---
# Dock
- name: Set Dock orientation to left
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left
  register: dock_defaults

# Keyboard
- name: Enable key repeat instead of press-and-hold
  community.general.osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false

- name: Set fast key repeat rate
  community.general.osx_defaults:
    key: KeyRepeat
    type: int
    value: 2

- name: Set short delay until key repeat
  community.general.osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15

# Finder
- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  register: finder_defaults_1

- name: Show all file extensions in Finder
  community.general.osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true
  register: finder_defaults_2

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  register: finder_defaults_3

- name: Use list view as default Finder style
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv
  register: finder_defaults_4

# Screenshots
- name: Create Screenshots directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Screenshots"
    state: directory
    mode: "0755"

- name: Save screenshots to ~/Screenshots
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_env.HOME }}/Screenshots"

- name: Disable screenshot shadow
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true

# Misc
- name: Disable Gatekeeper "Are you sure you want to open this application?" dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

- name: Disable auto-correct
  community.general.osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

# Restart affected apps to apply changes
- name: Restart Dock to apply defaults # noqa: no-changed-when
  ansible.builtin.command: killall Dock
  when: dock_defaults.changed

- name: Restart Finder to apply defaults # noqa: no-changed-when
  ansible.builtin.command: killall Finder
  when: >
    finder_defaults_1.changed or finder_defaults_2.changed or
    finder_defaults_3.changed or finder_defaults_4.changed
