---
- name: Configure Dock settings
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left

- name: Holding key down generates repeated key strokes
  community.general.osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
