---
- name: Setup iTerm location
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    # Should be path to the folder containing the file, not the file
    value: ~/.dotfiles/iterm2/

- name: Enable iTerm config preferences
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true

- name: Set dock position
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left

- name: Holding key down generates repeated key strokes
  community.general.osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
