name: CI

on: [push]

env:
  TERM: xterm

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker images
        run: make build

      - name: Run format checks
        run: make fmt_check

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install Ansible and ansible-lint
        run: uv pip install --system ansible ansible-lint

      - name: Install Ansible Galaxy requirements
        run: ansible-galaxy install -r requirements.yml

      - name: Run ansible-lint
        run: ansible-lint osx_defaults.yml

      - name: Run syntax check
        run: ansible-playbook osx_defaults.yml --syntax-check
